### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by ahmedfaizy** [hallowelt/migrate-confluence#1]
Hello,

I have a problem in running the script and i need your help as i don't have any experience in PHP to resolve it.
I got the following error when i ran the first cmd `migrate-confluence  analyze --src input/ --dest workspace/` the error is `PHP Warning:  require(/home/faizy/Downloads/migrate-confluence-main/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /home/faizy/Downloads/migrate-confluence-main/bin/migrate-confluence on line 4
PHP Fatal error:  require(): Failed opening required '/home/faizy/Downloads/migrate-confluence-main/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/faizy/Downloads/migrate-confluence-main/bin/migrate-confluence on line 4
`
And even when i commented out that line in the PHP script (I know it is not correct but i just want to know if i have more errors) i got the following error `PHP Fatal error:  Uncaught Error: Class 'HalloWelt\MediaWiki\Lib\Migration\CliApp' not found in /home/faizy/Downloads/migrate-confluence-main/bin/migrate-confluence:24
Stack trace:
#0 {main}
  thrown in /home/faizy/Downloads/migrate-confluence-main/bin/migrate-confluence on line 24
`
Could you please support me to override those errors?

**Comment by osnard** [comment]
Hi! Sorry, this is still work in progress. Should be released in the next weeks. Please stay tuned.

**Comment by ahmedfaizy** [comment]
Thank you Robert.

**Comment by osnard** [comment]
We have a first stable version now. You may try it!

**Comment by bombaata** [comment]
Hi, seems working ! You should just tell to first use **composer install** before using your tool ! We're not all developers here :)

**Comment by osnard** [comment]
Thanks! The pre-compiled PHAR is now available at https://github.com/hallowelt/migrate-confluence/releases
No need to use `composer install` anymore.
