### ISSUE TITLE
RecursiveDirectoryIterator error during convert

### ISSUE THREAD

**Issue by revansx** [hallowelt/migrate-confluence#111]
Hello. I have set up the directories as instructed and have been able to convert a few small confluence exports with no issue. My recent effort is to convert a Confluence export of about 30 GB. For this migration
`migrate-confluence analyze --src input/ --dest workspace/` 
and
`migrate-confluence extract --src input/ --dest workspace/`
ran fine but
`migrate-confluence convert --src input/ --dest workspace/`
fails with:
```
Source: /opt/data-meza/confluence-migrations/MyProject/input
Destination: /opt/data-meza/confluence-migrations/MyProject/workspace

Fetching file list ...
In BatchFileProcessorBase.php line 102:

RecursiveDirectoryIterator::__construct(/opt/data/confluence-migrations/MyProject/input/content/raw): Failed to open directory: No such file or directory

convert [--src SRC] [--dest [DEST]] [--config CONFIG]
```
interestingly, the `content/raw` exists in the "workspace" directory and not the "input" directory.

Please help! 

My site is:

- RHEL8
- MediaWiki 1.39.7 (374d95c)20:36, 23 April 2024
- PHP 8.1.28 (fpm-fcgi)
- MariaDB 10.3.39-MariaDB-log
- ICU 73.2
- Lua 5.1.5
- Pygments 2.11.2
- Elasticsearch 7.10.2
- SMW 4.1.3
- pandoc 3.1.13

**Comment by freephile** [comment]
I assume the 'input/content/raw' directory of a smaller migration does exist during the convert routine; and that only in this large migration the process fails with a missing 'input' directory.

It's a stab in the dark, but one possibility is that the disk is running out of inodes. Check your system with `df -i`

**Comment by revansx** [comment]
No shortage of inodes.

**Comment by revansx** [comment]
Silly me. Operator error. 

I didn't read the instructions clearly and was using "--src input/" rather than "--src workspace/".
