### ISSUE TITLE
installation instructions lead to 404

### ISSUE THREAD

**Issue by dmd** [hallowelt/migrate-confluence#121]
The first step in the README says:

> 1. Download `migrate-confluence.phar` from https://github.com/hallowelt/migrate-confluence/releases/tag/latest

But you don't actually have a "latest" tag, so that's 404.

**Comment by osnard** [comment]
Thanks! Fixed with https://github.com/hallowelt/migrate-confluence/commit/d259835a302d4a0134610a191c784fb6df2a027d
