### ISSUE TITLE
Please add instructions for using migrate-confluence

### ISSUE THREAD

**Issue by ststrat** [hallowelt/migrate-confluence#13]
When I follow the instructions it fails immediately because migrate-confluence/bin/migrate-confluence expects:

require __DIR__.'/../vendor/autoload.php';

Am I supposed to create a symlink to it?
Also:

$config = [
	'file-extension-whitelist' => [ 'xml' ],
	'analyzers' => [
		'HalloWelt\MigrateConfluence\Analyzer\ConfluenceAnalyzer::factory'
	],
	'extractors' => [
		'HalloWelt\MigrateConfluence\Extractor\ConfluenceExtractor::factory'
	],
	'converters' => [
		'HalloWelt\MigrateConfluence\Converter\ConfluenceConverter::factory'
	],
	'composers' => [
		'HalloWelt\MigrateConfluence\Composer\ConfluenceComposer::factory'
	]
];

As cloned from Github, migrate-confluence/src contains [Analyzer  Composer  Converter  Extractor  Utility]. Am i supposed to rename it?
Am I supposed to make a HalloWelt directory with those sub-directories?
Is migrate-confluence supposed to be installed as part of a larger project?
Am I supposed to edit the code to reflect my machine's configuration?
Please, I know this is free and open-source, but a little help? I am willing to contribute any changes I make and add to the README.md. I truly want this to work.

Thanks in advance, 
Your friend,
ststrat

**Comment by osnard** [comment]
Hi!

Please download and use https://github.com/hallowelt/migrate-confluence/releases/download/1.0.3/migrate-confluence.phar It contains everything you need.

I will update the `README.md`

**Comment by ststrat** [comment]
Thanks for your reply. I found a different way to migrate from Confluence to Mediawiki using html, because we had not invested in using the more sophisticated Confluence features.
I wish you continued success.

Best regards,
H. D. Akhond

**Comment by erhan-k** [comment]
Hi Osnard, has there been an update of your software? Do you have a version what should work with XML output of Confluence? I tried what you provided above but run into an error. Here is the error message:

(py3) erhan@remote1:~/tmp/confluence$ migrate-confluence analyze --src input/ --dest workspace/
Source: /home/erhan/tmp/confluence/input
Destination: /home/erhan/tmp/confluence/workspace

Fetching file list ...done.
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in phar:///usr/local/bin/migrate-confluence/src/Analyzer/ConfluenceAnalyzer.php:119
Stack trace:
#0 phar:///usr/local/bin/migrate-confluence/vendor/hallowelt/mediawiki-lib-migration/src/AnalyzerBase.php(67): HalloWelt\MigrateConfluence\Analyzer\ConfluenceAnalyzer->doAnalyze()
#1 phar:///usr/local/bin/migrate-confluence/src/Analyzer/ConfluenceAnalyzer.php(107): HalloWelt\MediaWiki\Lib\Migration\AnalyzerBase->analyze()
#2 phar:///usr/local/bin/migrate-confluence/vendor/hallowelt/mediawiki-lib-migration/src/Command/Analyze.php(50): HalloWelt\MigrateConfluence\Analyzer\ConfluenceAnalyzer->analyze()
#3 phar:///usr/local/bin/migrate-confluence/vendor/hallowelt/mediawiki-lib-migration/src/CliCommandBase.php(84): HalloWelt\MediaWiki\Lib\Migration\Command\Analyze->doProcessFile()
#4 phar:///usr/local/bin/migrate-confluence/vendor/hallowelt/mediawiki-lib-commandline-tools/src/Commands/BatchFileProcessorBase.php(122): HalloWelt\MediaWiki\Lib\Migration\CliCommandBase->process in phar:///usr/local/bin/migrate-confluence/src/Analyzer/ConfluenceAnalyzer.php on line 119
(py3) erhan@remote1:~/tmp/confluence$
