### ISSUE TITLE
No instructions on how to get HalloWelt\MediaWiki\Lib\Migration\CliApp

### ISSUE THREAD

**Issue by ststrat** [hallowelt/migrate-confluence#14]
the migrate-confluence skip has prerequisites mentioned no where in the project such as:

use HalloWelt\MediaWiki\Lib\Migration\CliApp;

Perhaps a clue as to where to get the requirements form would help.

**Comment by osnard** [comment]
You are right, sorry. All dependencies are manages by `composer`. Running `composer update` in the cloned repo will pull everything in. But actually end users are supposed to use the pre-build CLI tool anyways. This should already contain all required libraries.

I will update the README.md
