### ISSUE TITLE
Issue with `realpath` in PHAR archive

### ISSUE THREAD

**Issue by osnard** [hallowelt/migrate-confluence#17]
Using `realpath` within the PHAR file [1] leads to issues. this must be changed

[1] https://github.com/hallowelt/migrate-confluence/blob/92ad6476e001346b467a4af50e8a3ca8f9e500fc/src/Composer/ConfluenceComposer.php#L104-L106

**Comment by LotharHouben** [comment]
__DIR__ has a leading phar://, causing the trouble

Replacing:

104 $basepath = realpath( __DIR__ . '/_defaultpages/' ); 

with 

$string = pathinfo(__DIR__);
$_dir_ = parse_url($string['dirname']);
$basepath=$_dir_['host'].':/'.$_dir_['path'];

fixed the issue for me

**Comment by osnard** [comment]
Thank you very much! I will patch this as soon as possible and release a new version with a fixed PHAR.

**Comment by osnard** [comment]
Should be fixed with 1.0.7
