### ISSUE TITLE
Images on a page don't embed properly like they did in Confluence

### ISSUE THREAD

**Issue by mig5** [hallowelt/migrate-confluence#43]
When I import a page that was exported as XML from a Confluence space, that has embedded images in it, the content doesn't show the images in MediaWiki.

Instead, I get things like `[[File:|x250px]]` or `[[File:|x119px]]`.

According to the names that the images were given when imported (which seems to give a SPACE name, PageTitle name and image name as the file title), it ought to look like the following format:

```
[[File:SPACE PageTitleimagename.png|thumb]]
```

Yet, the images did import, and I can at least view them as 'Attachments' to the MediaWiki page. But the embed code hasn't worked.

Can you give any advice on how to fix this prior to the import into MediaWiki, other than obviously manually editing the `[[File]]` sections?

Also, alert/info boxes are working, but they show this code at the start of each alert box:

```
{{#if:|

'
|}}
```

... seems to be an issue with the 'SimplePanel' template which the Template:Note (Info, etc) inherit - I wonder if anyone else has come across this.

**Comment by osnard** [comment]
Thanks to reporting!

Actually the issue with the empty `[[File:|x250px]]` links has been addressed kist recently Can you tell which version of the tool you were using?

Regarding the `{{Info}}` templates: This is odd. Looks like the wikiext parsing was disabled in that template. I will check.

**Comment by mig5** [comment]
Thanks @osnard 

> Actually the issue with the empty [[File:|x250px]] links has been addressed kist recently Can you tell which version of the tool you were using?

I was using 1.0.8 because I couldn't use 1.1.0 due to https://github.com/hallowelt/migrate-confluence/issues/42

> Regarding the {{Info}} templates: This is odd. Looks like the wikiext parsing was disabled in that template. I will check.

Thanks. I worked around it for now by hacking around in the 'SimplePanel' template to remove some of the 'if' conditional logic, but it didn't feel like the right way..

**Comment by osnard** [comment]
Okay, thanks. We are working on releasing a new version that fixes the "missing file links" bug.

Could you maybe share the exact changes you applied to Template:SimplePanel?

**Comment by mig5** [comment]
@osnard thanks. I had to make SimplePanel like this, in order to get the appearance per the attached screenshot further below

```
<includeonly><templatestyles src="Template:SimplePanel.css" />
<div class="simplepanel {{{type|}}}" data-panel-type="{{{type|}}}">
<div class="simplepanel__icon">
<span role="img" aria-label="Panel {{{type|}}}">[[File:Icon-{{{type|info}}}.svg|link=]]</span>
</div>{{{title|}}}
<span class="simplepanel__heading">{{{title|}}}</span><br />
<div class="simplepanel__content">
{{{body|Add a <code>body</code> parameter}}}
</div>
</div>
</includeonly>
```

It originally looked like this:

```
<includeonly><templatestyles src="Template:SimplePanel.css" />
<div class="simplepanel {{{type|}}}" data-panel-type="{{{type|}}}">
<div class="simplepanel__icon">
<span role="img" aria-label="Panel {{{type|}}}">
[[File:Icon-{{{type|info}}}.svg|link=]]
</span>
</div>{{#if:{{{title|}}}|
<span class="simplepanel__heading">'''{{{title|}}}'''</span><br />
|}}<div class="simplepanel__content">
{{{body|Add a <code>body</code> parameter}}}
</div>
</div>
</includeonly>
```

![Screenshot_2022-02-15_10-04-30](https://user-images.githubusercontent.com/99173/153961689-d10ed644-8cdd-42e7-8317-b2a4f0ca2889.png)
![Screenshot_2022-02-15_10-05-00](https://user-images.githubusercontent.com/99173/153961693-1aa5ed65-3526-4cbd-b0c5-b644183440d7.png)

**Comment by osnard** [comment]
Could it be that you don't have [Extension:ParserFunctions](https://www.mediawiki.org/wiki/Extension:ParserFunctions) installed/enabled in your MediaWiki?

I have now added this to the list of recommended/required extensions: https://github.com/hallowelt/migrate-confluence/blob/217030ac84e922faaf55dd8e39abadd35db42b1f/README.md#recommended-mediawiki-extensions

**Comment by mig5** [comment]
@osnard - I have the ParserFunctions extension but it was not enabled. Thanks! I have enabled it and I will try another migration from Confluence and let you know if it makes a difference.

**Comment by mig5** [comment]
Actually, even without another migration, I reverted the SimplePanel template to undo my manual changes, and I can confirm the Note/Warning etc templates look better now. In fact, the spacing/padding is also better than it was. I think that was it, thanks!

Given the other image issue is reported to be fixed in an upcoming issue, I'll mark this closed. Thanks again.

**Comment by mig5** [comment]
Hi,

Just wanted to note that I tried the 1.1.1 release but I still get embeds like `[[File:|x250px]] ` instead of proper embedded images, on some pages but not others. 

I can't figure out why there is a difference - they are all .png images, even the ones that worked. 

In all cases (both successful embeds and not), the images are listed under 'Attachments'. 

Let me know if I can provide any other info that might help figure out why?
