### ISSUE TITLE
Huge input lookup

### ISSUE THREAD

**Issue by Alex-Allgood** [hallowelt/migrate-confluence#91]
> [root@wiki confluence]# migrate-confluence.phar analyze --src ./input/ --dest ./workspace/
> Source: /tmp/confluence/input
> Destination: /tmp/confluence/workspace
> 
> Fetching file list ...done.
> PHP Warning:  DOMDocument::load(): internal error: Huge input lookup in /tmp/confluence/input/entities.xml, line: 2042049 in phar:///usr/bin/migrate-confluence.phar/src/Analyzer/ConfluenceAnalyzer.php on line 168
> 
> Finding users
> 
> Finding namespaces
> 
> Finding pages
> 
> Finding attachments
> Done.
> 

Is my space too big, or is there something that I can do to fix this? I have tested this tool on another space and it worked. I tried to carry on and ignore the warning, but It ended up not being able to find a directory.

> [root@wiki confluence]# migrate-confluence extract --src input/ --dest workspace/
> Source: /tmp/confluence/input
> Destination: /tmp/confluence/workspace
> 
> Fetching file list ...done.
> PHP Warning:  DOMDocument::load(): internal error: Huge input lookup in /tmp/confluence/input/entities.xml, line: 2042049 in phar:///usr/bin/migrate-confluence.phar/src/Extractor/ConfluenceExtractor.php on line 35
> Done.
> [root@wiki confluence]# migrate-confluence convert --src workspace/ --dest workspace/
> Source: /tmp/confluence/workspace
> Destination: /tmp/confluence/workspace
> 
> Fetching file list ...
> In BatchFileProcessorBase.php line 102:
> 
>   RecursiveDirectoryIterator::__construct(/tmp/confluence/workspace/content/raw): failed to open dir: No such file or directory
> 
> 
> convert [--src SRC] [--dest [DEST]] [--config CONFIG]
>

**Comment by Alex-Allgood** [comment]
There was a permissions issue on the space and the tool ran properly after I cleaned that up.

**Comment by Alex-Allgood** [comment]
There was a permissions issue on the space and the tool ran properly after I cleaned that up.

**Comment by revansx** [comment]
@Alex-Allgood, hello. I'm having the same issue. When you say that there was a permission issue with the space, do you mean a permissions issue with the Confluence space prior to exporting? or do you mean a permissions issue with the migration workspace? I'm trying to figure out if I need to ask my client to alter their Confluence system and re-export or if I need to figure out something that needs to be done on the migrations input and workspace data. Thank you!
