### ISSUE TITLE
Date macro doesn't get converted

### ISSUE THREAD

**Issue by Tedderouni** [hallowelt/migrate-confluence#96]
The Date macro doesn't seem to get converted, it just ends up as blank space in the converted page.

I'm referring to this Date macro:

<img width="318" alt="image" src="https://github.com/hallowelt/migrate-confluence/assets/3107348/3addecce-5dbe-4017-871d-b25d406c042b">

In Confluence it prompts with a Calendar date picker when you select from the menu shown above or just use the `//` shortcut:

<img width="280" alt="image" src="https://github.com/hallowelt/migrate-confluence/assets/3107348/2439c373-40a9-427b-9ec3-7b638c3c90b0">

...which then gets displayed like this in Confluence:

<img width="127" alt="image" src="https://github.com/hallowelt/migrate-confluence/assets/3107348/4f894bcc-897b-4d53-9d29-ac9dab3680e7">

This doesn't make it into MediaWiki in my attempts. I'm using Confluence Server 8.5.5 and migrate-confluence 1.2.1.

**Comment by osnard** [comment]
Has been released since
